
# cargo-vet config file

[cargo-vet]
version = "0.10"

[policy.uds-kit]
audit-as-crates-io = true

[[exemptions.bitflags]]
version = "2.13.1"
criteria = "safe-to-run"

[[exemptions.bytes]]
version = "1.12.1"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.4"
criteria = "safe-to-run"

[[exemptions.errno]]
version = "0.3.14"
criteria = "safe-to-run"

[[exemptions.fastrand]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.getrandom]]
version = "0.4.3"
criteria = "safe-to-run"

[[exemptions.libc]]
version = "0.2.189"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.12.1"
criteria = "safe-to-run"

[[exemptions.mio]]
version = "1.2.3"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.4"
criteria = "safe-to-run"

[[exemptions.pin-project-lite]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.107"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.47"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "6.0.0"
criteria = "safe-to-run"

[[exemptions.rustix]]
version = "1.1.4"
criteria = "safe-to-run"

[[exemptions.socket2]]
version = "0.6.5"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "3.0.5"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.27.0"
criteria = "safe-to-run"

[[exemptions.thiserror]]
version = "2.0.20"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.20"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.53.1"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "2.7.2"
criteria = "safe-to-deploy"

[[exemptions.uds-kit]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.24"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.1+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.windows-link]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.61.2"
criteria = "safe-to-deploy"
